### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by cala**
Few mangos-one fixes ported to zero. Especially fix trainers level for druids where all feral skills were available at level 10.

### CODE REVIEW

**Comment by ghost** [comment]
Can you resubmit this without the reverts? :) A bit too many in there. Thanks a lot.

**Comment by cala** [comment]
I thought github would not include the revert in the pull request. I was wrong. As soon as I find how to select which commit to include/exclude from a pull request, I'll submit it again.

**Comment by ghost** [comment]
If you can't find it, I'll manually cherry pick em :)

**Comment by cala** [comment]
Ok, fixed. I'm submitting a new and cleaner pull request. This old one has to be closed.

**Pull request closed without merging**
